name: Build app all platforms

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies (Linux)
        run: sudo apt-get update && sudo apt-get install -y patchelf

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Build with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          script-name: main.py
          mode: standalone
          extra-options: >-
            --enable-plugin=pyqt5
            --follow-imports
            --include-data-dir=vowspace/assets=vowspace/assets

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vowspace-${{ runner.os }}-py${{ matrix.python-version }}
          path: |
            *.dist/**
            *.bin